# Generated by Django 4.2.25 on 2025-11-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalreport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='finalreport',
            unique_together={('study_id', 'site')},
        ),
        migrations.AlterModelTable(
            name='finalreport',
            table='final_reports',
        ),
    ]
