# Generated by Django 4.2.25 on 2025-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0002_alter_finalreport_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftreport',
            name='test_pdf',
            field=models.FileField(blank=True, null=True, upload_to='test_pdfs/'),
        ),
    ]
