# Generated by Django 4.2.25 on 2025-11-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0003_draftreport_test_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='processlog',
            name='triggered_by',
            field=models.CharField(blank=True, help_text='User or system that generated the log.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='product',
            field=models.CharField(blank=True, help_text='Experimental product of the leg.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='region',
            field=models.CharField(blank=True, help_text='Region of the manufacturing site.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='response',
            field=models.CharField(blank=True, help_text='Survey response ID, if applicable.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='site',
            field=models.CharField(blank=True, help_text='Manufacturing site of the experimental product.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='state',
            field=models.CharField(blank=True, help_text='Identifier of the type / criticality of the log event.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='study',
            field=models.CharField(blank=True, help_text='Study ID associated with the log event.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='text',
            field=models.TextField(blank=True, help_text='Text description / qualifier of the log event.', null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time that the log event was generated.'),
        ),
    ]
