# Generated by Django 4.2.25 on 2025-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0005_alter_processlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
