# Generated by Django 4.2.25 on 2025-11-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0006_alter_processlog_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processlog',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='approval',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
