# Generated by Django 4.2.25 on 2025-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0007_remove_processlog_updated_by_approval_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='processlog',
            name='updated_by',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
