# Generated by Django 4.2.25 on 2025-11-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthology', '0008_alter_processlog_options_processlog_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
